### ISSUE TITLE
New YARA Rule

### ISSUE THREAD

**Issue by hoangprod** [Jarijaas/RS3Bot#1]
Hey Jarijaas,

First and foremost, thank you for the amazing project. This project and its current yara rule have helped me move a bit forward in term of RS3 NXT Client reverse engineering. However, I could not find a good email/discord/method to contact you - i apologize for the inconvenience of making an issue :(

However, I have a few questions in regard to how did you go about discovering some of the functions such as DispatchMessage/etc and help me maintain this project. Thanks a lot! You can contact me at discord fs0x30#4711

**Comment by Jarijaas** [comment]
Hey,

Added you on discord
